import type { StudentFieldDefinition, StudentWithRelations } from '../types/domain';
import { formatDateLabel } from './dates';

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function row(label: string, value: unknown): string {
  return `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value || 'Not provided')}</td></tr>`;
}

export function buildStudentPdfHtml(
  student: StudentWithRelations,
  fields: StudentFieldDefinition[],
  generatedBy = 'FlowPilot',
): string {
  const customRows = fields
    .map((field) => row(field.label, student.custom_values[field.field_key]))
    .join('');
  const fullName = [student.first_name, student.middle_name, student.last_name].filter(Boolean).join(' ');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { color: #17211B; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding: 28px; }
      header { border-bottom: 2px solid #16695B; margin-bottom: 20px; padding-bottom: 12px; }
      h1 { font-size: 28px; margin: 0; }
      h2 { color: #16695B; font-size: 18px; margin: 6px 0 0; }
      table { border-collapse: collapse; margin-top: 18px; width: 100%; }
      th, td { border-bottom: 1px solid #DDE6DC; padding: 10px 8px; text-align: left; vertical-align: top; }
      th { color: #607064; width: 34%; }
      footer { color: #607064; font-size: 12px; margin-top: 28px; text-align: center; }
    </style>
  </head>
  <body>
    <header>
      <h1>${escapeHtml(fullName)}</h1>
      <h2>${escapeHtml(student.school_name || 'Student Record')}</h2>
    </header>
    <table>
      ${row('Student Number', student.student_number)}
      ${row('Class', [student.class_name, student.class_section].filter(Boolean).join(' - '))}
      ${row('Academic Year', student.academic_year_name)}
      ${row('Record Date', formatDateLabel(student.record_date))}
      ${row('Date of Birth', formatDateLabel(student.date_of_birth))}
      ${row('Age', student.age)}
      ${row('Gender', student.gender)}
      ${row('Email', student.email)}
      ${row('Phone', student.phone)}
      ${row('Guardian Name', student.guardian_name)}
      ${row('Guardian Phone', student.guardian_phone)}
      ${row('Address', student.address)}
      ${row('Notes', student.notes)}
      ${customRows}
    </table>
    <footer>Generated by ${escapeHtml(generatedBy)} on ${escapeHtml(new Date().toLocaleString())}</footer>
  </body>
</html>`;
}

export function buildStudentsSummaryPdfHtml(
  title: string,
  students: StudentWithRelations[],
  fields: StudentFieldDefinition[],
  generatedBy = 'FlowPilot',
): string {
  const headers = ['Name', 'Student No.', 'Class', 'Guardian', 'Phone'].concat(fields.map((field) => field.label));
  const rows = students
    .map((student) => {
      const values: unknown[] = [
        [student.first_name, student.last_name].filter(Boolean).join(' '),
        student.student_number,
        [student.class_name, student.class_section].filter(Boolean).join(' - '),
        student.guardian_name,
        student.guardian_phone,
        ...fields.map((field) => student.custom_values[field.field_key]),
      ];
      return `<tr>${values.map((value) => `<td>${escapeHtml(value || '')}</td>`).join('')}</tr>`;
    })
    .join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { color: #17211B; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding: 24px; }
      h1 { border-bottom: 2px solid #16695B; font-size: 24px; margin: 0 0 16px; padding-bottom: 12px; }
      table { border-collapse: collapse; font-size: 11px; width: 100%; }
      th, td { border: 1px solid #DDE6DC; padding: 7px; text-align: left; }
      th { background: #DFF2EC; }
      footer { color: #607064; font-size: 11px; margin-top: 20px; text-align: center; }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(title)}</h1>
    <table>
      <thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join('')}</tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <footer>${students.length} records generated by ${escapeHtml(generatedBy)} on ${escapeHtml(new Date().toLocaleString())}</footer>
  </body>
</html>`;
}
