CREATE TABLE IF NOT EXISTS public.organization_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email text NOT NULL CHECK (email = lower(btrim(email)) AND position('@' IN email) > 1),
  role text NOT NULL CHECK (role IN ('ORG_ADMIN', 'SCHOOL_ADMIN', 'STAFF')),
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')),
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  accepted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pending_organization_invitation_email
  ON public.organization_invitations (organization_id, lower(email))
  WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_organization_invitations_email
  ON public.organization_invitations (lower(email), status, expires_at);

ALTER TABLE public.organization_members
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS display_name text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.organization_members AS membership
SET email = lower(auth_user.email)
FROM auth.users AS auth_user
WHERE membership.user_id = auth_user.id
  AND membership.email IS NULL;

CREATE TABLE IF NOT EXISTS public.access_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('INVITE_SENT', 'INVITATION_REVOKED', 'INVITATION_ACCEPTED', 'ROLE_CHANGED', 'MEMBER_REMOVED')),
  target_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  target_email text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_access_audit_log_organization
  ON public.access_audit_log (organization_id, created_at DESC);

DROP TRIGGER IF EXISTS organization_members_set_updated_at ON public.organization_members;
CREATE TRIGGER organization_members_set_updated_at
BEFORE UPDATE ON public.organization_members
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS organization_invitations_set_updated_at ON public.organization_invitations;
CREATE TRIGGER organization_invitations_set_updated_at
BEFORE UPDATE ON public.organization_invitations
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC;
GRANT USAGE ON SCHEMA private TO authenticated;

CREATE OR REPLACE FUNCTION private.is_org_admin(target_organization_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.organization_members
    WHERE organization_id = target_organization_id
      AND user_id = (SELECT auth.uid())
      AND role IN ('SUPER_ADMIN', 'ORG_ADMIN')
  );
$$;

CREATE OR REPLACE FUNCTION private.can_manage_school(target_school_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.schools
    JOIN public.organization_members
      ON organization_members.organization_id = schools.organization_id
    WHERE schools.id = target_school_id
      AND organization_members.user_id = (SELECT auth.uid())
      AND organization_members.role IN ('SUPER_ADMIN', 'ORG_ADMIN', 'SCHOOL_ADMIN')
  );
$$;

REVOKE ALL ON FUNCTION private.is_org_admin(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION private.can_manage_school(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.is_org_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_school(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.hook_require_invitation(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  requested_email text := lower(btrim(event->'user'->>'email'));
BEGIN
  IF requested_email IS NULL OR requested_email = '' THEN
    RETURN jsonb_build_object(
      'error', jsonb_build_object(
        'http_code', 403,
        'message', 'FlowPilot registration requires an invited email address.'
      )
    );
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.organization_invitations
    WHERE email = requested_email
      AND status = 'PENDING'
      AND expires_at > now()
  ) THEN
    RETURN '{}'::jsonb;
  END IF;

  RETURN jsonb_build_object(
    'error', jsonb_build_object(
      'http_code', 403,
      'message', 'This email has not been invited to FlowPilot. Ask an organization administrator for access.'
    )
  );
END;
$$;

GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.hook_require_invitation(jsonb) TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.hook_require_invitation(jsonb) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.accept_flowpilot_invitations()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  invitation_record public.organization_invitations%ROWTYPE;
  normalized_email text := lower(btrim(NEW.email));
BEGIN
  IF normalized_email IS NULL OR normalized_email = '' THEN
    RETURN NEW;
  END IF;

  FOR invitation_record IN
    SELECT *
    FROM public.organization_invitations
    WHERE email = normalized_email
      AND status = 'PENDING'
      AND expires_at > now()
    FOR UPDATE
  LOOP
    INSERT INTO public.organization_members (
      organization_id,
      user_id,
      role,
      email,
      display_name
    )
    VALUES (
      invitation_record.organization_id,
      NEW.id,
      invitation_record.role,
      normalized_email,
      COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name')
    )
    ON CONFLICT (organization_id, user_id) DO UPDATE SET
      role = EXCLUDED.role,
      email = EXCLUDED.email,
      display_name = COALESCE(EXCLUDED.display_name, organization_members.display_name),
      updated_at = now();

    UPDATE public.organization_invitations
    SET status = 'ACCEPTED', accepted_by = NEW.id, last_error = NULL, updated_at = now()
    WHERE id = invitation_record.id;

    INSERT INTO public.access_audit_log (
      organization_id,
      actor_user_id,
      action,
      target_user_id,
      target_email
    )
    VALUES (
      invitation_record.organization_id,
      invitation_record.invited_by,
      'INVITATION_ACCEPTED',
      NEW.id,
      normalized_email
    );
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS accept_flowpilot_invitations_on_auth_user ON auth.users;
CREATE TRIGGER accept_flowpilot_invitations_on_auth_user
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.accept_flowpilot_invitations();

REVOKE EXECUTE ON FUNCTION public.accept_flowpilot_invitations() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.sync_flowpilot_member_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.organization_members
  SET
    email = lower(NEW.email),
    display_name = COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', display_name),
    updated_at = now()
  WHERE user_id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_flowpilot_member_email_on_auth_user ON auth.users;
CREATE TRIGGER sync_flowpilot_member_email_on_auth_user
AFTER UPDATE OF email, raw_user_meta_data ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.sync_flowpilot_member_email();

REVOKE EXECUTE ON FUNCTION public.sync_flowpilot_member_email() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.bootstrap_first_owner(
  target_email text,
  target_organization_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  normalized_email text := lower(btrim(target_email));
  target_user_id uuid;
  invitation_id uuid;
BEGIN
  IF normalized_email IS NULL OR normalized_email = '' OR position('@' IN normalized_email) <= 1 THEN
    RAISE EXCEPTION 'A valid owner email is required.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.organizations WHERE id = target_organization_id
  ) THEN
    RAISE EXCEPTION 'Organization does not exist.';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.organization_members
    WHERE organization_id = target_organization_id
      AND role IN ('SUPER_ADMIN', 'ORG_ADMIN')
      AND COALESCE(email, '') <> normalized_email
  ) THEN
    RAISE EXCEPTION 'This organization already has a different owner. Use Team Access in the app.';
  END IF;

  SELECT id INTO target_user_id
  FROM auth.users
  WHERE lower(email) = normalized_email
  ORDER BY created_at ASC
  LIMIT 1;

  IF target_user_id IS NOT NULL THEN
    INSERT INTO public.organization_members (organization_id, user_id, role, email)
    VALUES (target_organization_id, target_user_id, 'ORG_ADMIN', normalized_email)
    ON CONFLICT (organization_id, user_id) DO UPDATE SET
      role = 'ORG_ADMIN',
      email = EXCLUDED.email,
      updated_at = now();
    RETURN target_user_id;
  END IF;

  INSERT INTO public.organization_invitations (
    organization_id,
    email,
    role,
    status,
    expires_at
  )
  VALUES (
    target_organization_id,
    normalized_email,
    'ORG_ADMIN',
    'PENDING',
    now() + interval '30 days'
  )
  ON CONFLICT (organization_id, lower(email)) WHERE status = 'PENDING'
  DO UPDATE SET
    role = 'ORG_ADMIN',
    expires_at = now() + interval '30 days',
    last_error = NULL,
    updated_at = now()
  RETURNING id INTO invitation_id;

  RETURN invitation_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.bootstrap_first_owner(text, uuid) FROM PUBLIC, anon, authenticated;

ALTER TABLE public.organization_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can read their memberships" ON public.organization_members;
CREATE POLICY "Members can read their own membership and admins can read their organization"
  ON public.organization_members
  FOR SELECT
  TO authenticated
  USING (
    user_id = (SELECT auth.uid())
    OR private.is_org_admin(organization_id)
  );

CREATE POLICY "Admins can read organization invitations"
  ON public.organization_invitations
  FOR SELECT
  TO authenticated
  USING (private.is_org_admin(organization_id));

CREATE POLICY "Admins can read organization access audit logs"
  ON public.access_audit_log
  FOR SELECT
  TO authenticated
  USING (private.is_org_admin(organization_id));

REVOKE ALL ON public.organization_invitations FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.organization_invitations FROM authenticated;
GRANT SELECT ON public.organization_invitations TO authenticated;

REVOKE ALL ON public.access_audit_log FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.access_audit_log FROM authenticated;
GRANT SELECT ON public.access_audit_log TO authenticated;

DROP POLICY IF EXISTS "Schools are scoped to organization members" ON public.schools;
CREATE POLICY "Organization members can read schools"
  ON public.schools FOR SELECT TO authenticated
  USING (public.is_org_member(organization_id));
CREATE POLICY "School admins can create schools"
  ON public.schools FOR INSERT TO authenticated
  WITH CHECK (private.is_org_admin(organization_id));
CREATE POLICY "School admins can update schools"
  ON public.schools FOR UPDATE TO authenticated
  USING (private.can_manage_school(id))
  WITH CHECK (private.is_org_admin(organization_id));
CREATE POLICY "Organization admins can delete schools"
  ON public.schools FOR DELETE TO authenticated
  USING (private.is_org_admin(organization_id));

DROP POLICY IF EXISTS "Academic years are scoped to school organizations" ON public.academic_years;
CREATE POLICY "Organization members can read academic years"
  ON public.academic_years FOR SELECT TO authenticated
  USING (private.can_manage_school(school_id) OR EXISTS (
    SELECT 1 FROM public.schools
    WHERE schools.id = academic_years.school_id
      AND public.is_org_member(schools.organization_id)
  ));
CREATE POLICY "School admins can create academic years"
  ON public.academic_years FOR INSERT TO authenticated
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can update academic years"
  ON public.academic_years FOR UPDATE TO authenticated
  USING (private.can_manage_school(school_id))
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can delete academic years"
  ON public.academic_years FOR DELETE TO authenticated
  USING (private.can_manage_school(school_id));

DROP POLICY IF EXISTS "Classes are scoped to school organizations" ON public.classes;
CREATE POLICY "Organization members can read classes"
  ON public.classes FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.schools
    WHERE schools.id = classes.school_id
      AND public.is_org_member(schools.organization_id)
  ));
CREATE POLICY "School admins can create classes"
  ON public.classes FOR INSERT TO authenticated
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can update classes"
  ON public.classes FOR UPDATE TO authenticated
  USING (private.can_manage_school(school_id))
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can delete classes"
  ON public.classes FOR DELETE TO authenticated
  USING (private.can_manage_school(school_id));

DROP POLICY IF EXISTS "Student field definitions are scoped to school organizations" ON public.student_field_definitions;
CREATE POLICY "Organization members can read student field definitions"
  ON public.student_field_definitions FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.schools
    WHERE schools.id = student_field_definitions.school_id
      AND public.is_org_member(schools.organization_id)
  ));
CREATE POLICY "School admins can create student field definitions"
  ON public.student_field_definitions FOR INSERT TO authenticated
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can update student field definitions"
  ON public.student_field_definitions FOR UPDATE TO authenticated
  USING (private.can_manage_school(school_id))
  WITH CHECK (private.can_manage_school(school_id));
CREATE POLICY "School admins can delete student field definitions"
  ON public.student_field_definitions FOR DELETE TO authenticated
  USING (private.can_manage_school(school_id));
