import { buildStudentsCsv, escapeCsvValue } from '../src/utils/csv';
import { calculateAge, isValidDateString } from '../src/utils/dates';
import { buildStudentPdfHtml } from '../src/utils/html';
import { shouldRetryQueueItem } from '../src/features/sync/retryPolicy';
import { sanitizeRemotePayload } from '../src/features/sync/remotePayload';
import { getAuthCallbackFlow, parseAuthCallbackUrl } from '../src/features/auth/authCallback';
import { authEmailOnlySchema, authEmailSchema, inviteAcceptanceSchema, studentSchema } from '../src/validation/schemas';
import type { StudentFieldDefinition, StudentWithRelations } from '../src/types/domain';

const student: StudentWithRelations = {
  id: '11111111-1111-4111-8111-111111111111',
  organization_id: '00000000-0000-4000-8000-000000000001',
  school_id: '00000000-0000-4000-8000-000000000101',
  class_id: '00000000-0000-4000-8000-000000000301',
  academic_year_id: '00000000-0000-4000-8000-000000000201',
  student_number: 'SR-100',
  first_name: 'Asha',
  middle_name: null,
  last_name: 'Khan',
  preferred_name: null,
  date_of_birth: '2015-06-15',
  age: 11,
  gender: 'F',
  email: null,
  phone: null,
  guardian_name: 'Nadia Khan',
  guardian_phone: '+91 90000 00000',
  address: null,
  photo_url: null,
  photo_local_path: null,
  record_date: '2026-08-09',
  notes: 'Needs, CSV escaping',
  created_by: null,
  created_at: '2026-08-09T00:00:00.000Z',
  updated_at: '2026-08-09T00:00:00.000Z',
  deleted_at: null,
  sync_status: 'PENDING',
  last_synced_at: null,
  school_name: 'Government High School',
  class_name: 'Grade 5',
  class_section: 'A',
  academic_year_name: '2026-2027',
  custom_values: {
    blood_group: 'A+',
  },
};

const fields: StudentFieldDefinition[] = [
  {
    id: '22222222-2222-4222-8222-222222222222',
    school_id: student.school_id,
    field_key: 'blood_group',
    label: 'Blood Group',
    field_type: 'SELECT',
    is_required: false,
    display_order: 1,
    is_active: true,
    options: ['A+', 'B+'],
    created_at: student.created_at,
    updated_at: student.updated_at,
    deleted_at: null,
    sync_status: 'SYNCED',
    last_synced_at: null,
  },
];

describe('core utilities', () => {
  it('calculates age using birthday boundaries', () => {
    expect(calculateAge('2015-06-15', new Date('2026-06-14T12:00:00Z'))).toBe(10);
    expect(calculateAge('2015-06-15', new Date('2026-06-15T12:00:00Z'))).toBe(11);
  });

  it('rejects impossible calendar dates before they reach Supabase', () => {
    expect(isValidDateString('1989-09-34')).toBe(false);
    expect(isValidDateString('2025-02-29')).toBe(false);
    expect(isValidDateString('2024-02-29')).toBe(true);
    expect(
      studentSchema.safeParse({ school_id: student.school_id, first_name: 'Asha', date_of_birth: '1989-09-34' })
        .success,
    ).toBe(false);
  });

  it('escapes CSV values safely', () => {
    expect(escapeCsvValue('Needs, quotes "now"')).toBe('"Needs, quotes ""now"""');
  });

  it('builds CSV exports with custom fields', () => {
    const csv = buildStudentsCsv([student], fields);
    expect(csv).toContain('Blood Group');
    expect(csv).toContain('"Needs, CSV escaping"');
    expect(csv).toContain('A+');
  });

  it('builds student PDF HTML without leaking raw markup', () => {
    const html = buildStudentPdfHtml({ ...student, first_name: '<Asha>' }, fields);
    expect(html).toContain('&lt;Asha&gt;');
    expect(html).toContain('Generated by FlowPilot');
  });

  it('validates and derives student age', () => {
    const parsed = studentSchema.parse({
      school_id: student.school_id,
      first_name: 'Asha',
      date_of_birth: '2015-06-15',
      record_date: '2026-08-09',
    });
    expect(parsed.age).toBeGreaterThanOrEqual(10);
  });

  it('accepts null optional student text fields', () => {
    const parsed = studentSchema.parse({
      school_id: student.school_id,
      first_name: 'Asha',
      preferred_name: null,
      middle_name: null,
      last_name: null,
      email: null,
    });
    expect(parsed.preferred_name).toBeNull();
    expect(parsed.email).toBeNull();
  });

  it('normalizes auth email and validates credentials', () => {
    expect(authEmailSchema.parse({ email: ' Staff@Example.COM ', password: 'secret1' })).toEqual({
      email: 'staff@example.com',
      password: 'secret1',
    });
    expect(authEmailSchema.safeParse({ email: 'not-an-email', password: '123' }).success).toBe(false);
    expect(authEmailOnlySchema.parse({ email: ' STAFF@example.com ' })).toEqual({ email: 'staff@example.com' });
  });

  it('requires a strong matching password when an invitation is accepted', () => {
    expect(
      inviteAcceptanceSchema.safeParse({ displayName: 'School Admin', password: 'secure123', confirmPassword: 'secure123' })
        .success,
    ).toBe(true);
    expect(
      inviteAcceptanceSchema.safeParse({ displayName: 'School Admin', password: 'short', confirmPassword: 'short' })
        .success,
    ).toBe(false);
    expect(
      inviteAcceptanceSchema.safeParse({ displayName: 'School Admin', password: 'secure123', confirmPassword: 'different' })
        .success,
    ).toBe(false);
  });

  it('distinguishes invitation callbacks from ordinary signed-in routes', () => {
    expect(getAuthCallbackFlow('http://localhost:8081/accept-invite?flow=invite')).toBe('invite');
    expect(getAuthCallbackFlow('flowpilot://accept-invite#access_token=token&type=invite')).toBe('invite');
    expect(getAuthCallbackFlow('http://localhost:8081/accept-invite')).toBeNull();
  });

  it('reads Supabase invitation credentials from the URL fragment', () => {
    expect(
      parseAuthCallbackUrl(
        'https://flowpilot-mobile.expo.app/accept-invite?flow=invite#access_token=access-value&refresh_token=refresh-value&type=invite',
      ),
    ).toEqual({
      flow: 'invite',
      code: undefined,
      accessToken: 'access-value',
      refreshToken: 'refresh-value',
      error: undefined,
    });
  });

  it('limits sync retries', () => {
    expect(shouldRetryQueueItem({ status: 'FAILED', retry_count: 2 })).toBe(true);
    expect(shouldRetryQueueItem({ status: 'FAILED', retry_count: 3 })).toBe(false);
    expect(shouldRetryQueueItem({ status: 'SYNCED', retry_count: 0 })).toBe(false);
  });

  it('removes local relation fields from student sync payloads', () => {
    expect(
      sanitizeRemotePayload('students', {
        id: student.id,
        first_name: student.first_name,
        academic_year_name: student.academic_year_name,
        school_name: student.school_name,
        custom_values: student.custom_values,
        sync_status: student.sync_status,
      }),
    ).toEqual({ id: student.id, first_name: student.first_name });
  });
});
